version: '3.8'
services:
  prometheus:
    image: docker.io/prom/prometheus:v2.53.1
    container_name: prometheus
    ports:
      - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped
    networks:
      network:
        ipv4_address: 172.18.0.101

  grafana:
    # image: docker.io/grafana/grafana-oss:11.1.3
    image: grafana/grafana:main-ubuntu
    container_name: grafana
    expose:
      - "3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    environment:
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:25
      - GF_SMTP_FROM_ADDRESS=letanphat15122004@gmail.com
      - GF_SMTP_FROM_NAME=phat
      - GF_SMTP_PASSWORD=ttuhhbjyxwpptbwn
      - GF_SMTP_USER=letanphat15122004

    networks:
      network:
        ipv4_address: 172.18.0.102
  telegraf:
    image: telegraf
    container_name: telegraf
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ~/Documents/nginx/access.log:/var/log/nginx/access.log:ro
    expose:
      - "9094"
    networks:
      network:
        ipv4_address: 172.18.0.103

  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.8.2
    container_name: node_exporter
    command: "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    expose:
      - "9100"
    volumes:
      - /:/host:ro,rslave
    networks:
    - network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.50.0
    container_name: cadvisor
    # ports:
    #   - 8080:8080
    expose:
      - "8080"
    volumes:
      - /:/rootfs:ro
      - /run:/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped
    networks:
    - network

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
networks:
  network:
    name: webserver
    external: true