version: '3.8'
services:


  prometheus:
    image: prom/prometheus:v2.53.1
    container_name: prometheus
    expose:
      - "9090"
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheuss-data:/prometheus
      - ./config/alertrule.yml:/etc/prometheus/alertrule.yml:ro
    restart: unless-stopped
    networks:
      network:
        ipv4_address: 172.18.0.101



  grafana:
    image: grafana/grafana:main-ubuntu
    container_name: grafana
    expose:
      - "3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      network:
        ipv4_address: 172.18.0.102



  telegraf:
    image: telegraf
    container_name: telegraf
    expose:
      - "9094"
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ~/Documents/nginx/access.log:/var/log/nginx/access.log:ro
    networks:
      network:
        ipv4_address: 172.18.0.103



  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.8.2
    container_name: node_exporter
    command: "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    expose:
      - "9100"
    volumes:
      - /:/host:ro,rslave
    networks:
      network:
        ipv4_address: 172.18.0.104



  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.50.0
    container_name: cadvisor
    expose:
      - "8080"
    volumes:
      - /:/rootfs:ro
      - /run:/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped
    networks:
      network:
        ipv4_address: 172.18.0.105



  alertmanager:
    image: prom/alertmanager
    restart: unless-stopped
    expose:
      - "9093"
    volumes:
      - ./config:/config
      - alertmanager-data:/data
    command: "--config.file=/config/alertmanager.yml"
    networks:
      network:
        ipv4_address: 172.18.0.106

volumes:
  prometheuss-data:
  grafana-data:
  alertmanager-data:

networks:
  network:
    name: webserver
    external: true



#   environment:
# - GF_SMTP_ENABLED=true
# - GF_SMTP_HOST=smtp.gmail.com:25
# - GF_SMTP_FROM_ADDRESS=letanphat15122004@gmail.com
# - GF_SMTP_FROM_NAME=phat
# - GF_SMTP_PASSWORD=ttuhhbjyxwpptbwn
# - GF_SMTP_USER=letanphat15122004