groups:
- name: node_exporter
  rules:

  # Alert if Node exporter is down
  - alert: NodeDown
    expr: up == 0
    for: 7s
    labels:
      severity: critical
    annotations:
      title: Node {{ $labels.instance }} is down
      description: Failed to scrape {{ $labels.job }} on {{ $labels.instance }}. Node seems down.
  
  # Alert if any node has a CPU usage above 80% for more than 5 minutes
  - alert: HighCPUUsage
    expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage on {{ $labels.instance }}"
      description: "{{ $labels.instance }} has a CPU usage of {{ $value }}% for more than 5 minutes"

  # Alert if any node has a RAM usage above 90% for more than 5 minutes
  - alert: HighRAMUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 90
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High RAM usage on {{ $labels.instance }}"
      description: "{{ $labels.instance }} has a RAM usage of {{ $value }}% for more than 5 minutes"

  # Alert if any node has a disk usage above 80% for more than 5 minutes
  - alert: HighDiskUsage
    expr: node_filesystem_avail_bytes / node_filesystem_size_bytes * 100 < 20
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High disk usage on {{ $labels.instance }} ({{ $labels.device }})"
      description: "{{ $labels.instance }} has a disk usage of {{ $value }}% for more than 5 minutes on device {{ $labels.device }}"

- name: cadvisor
  rules:

  # Alert if Nginx container experiences downtime within 7s
  - alert: Nginx
    expr: time() - container_last_seen{name="nginx"} > 10
    for: 7s
    labels:
      severity: critical
    annotations:
      summary: "Nginx has encountered problem"
      description: "Nginx is experiencing downtime"
      title: Nginx is down