global:
  resolve_timeout: 5m
  # smtp_smarthost: 'smtp.gmail.com:25'
  # smtp_from: 'letanphat15122004@gmail.com'
  # smtp_auth_username: 'letanphat15122004'
  # smtp_auth_password: 'ttuhhbjyxwpptbwn'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 3600s
  receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: 'letanphat15122004@gmail.com'
    from: 'letanphat15122004@gmail.com'
    smarthost: 'smtp.gmail.com:587'
    auth_username: 'letanphat15122004'
    auth_identity: 'letanphat15122004'
    auth_password: 'nwtifvhtluimljhj'