global:
  scrape_interval: 5s
  evaluation_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']
rule_files:
  - "alertrule.yml"
  
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'telegraf'
    static_configs:
      - targets: ['telegraf:9094']